pages:
  - Home: index.md
  - Get Started: get-started.md
  - Development workflow: workflow.md
  - Learning Tips: learning-tips.md
  - Tech Stack: tech-stack.md
  - Plan: plan.md
  # - Stash: stash.md

site_name: Codecats CV
repo_url: https://github.com/obestwalter/codecats-cv
strict: True
theme: material
extra:
  logo: _static/logo.png
  author:
    github: obestwalter
    twitter: obestwalter
extra_css:
  - _static/extra.css
markdown_extensions:
    - admonition
    - toc:
        permalink: True #¶
